// <auto-generated />
namespace T1908E_WAD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NastyCreateTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NastyCreateTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003171328425_NastyCreateTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
